AllCops:
  Exclude:
    - 'bin/*'
    - 'config/*'
    - 'db/*'
    - 'lib/*'
    - 'spec/*'
    - 'vendor/*'

  Include:
    - 'app/channels/*'
    - 'app/components/*'
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/jobs/*'
    - 'app/mailers/*'
    - 'app/models/*'


Style/Documentation:
  Enabled: false
